### ISSUE TITLE
Tournure de phrases

### ISSUE THREAD

**Issue by angelfs** [sKyoKun/symfonyMemo#1]
Ce qui doit se trouver dans la base de données après le retour API => Ce que la BDD doit contenir comme données
meme tournure pour les autres ? 
Ce qui doit se trouver dans les files RabbitMQ (messenger) => Ce que les files RabbitMQ (messenger) doit contenir comme message
Ce qui doit se trouver dans les logs => Ce que les logs doivent contenir comme message

**Comment by sKyoKun** [comment]
Done in https://github.com/sKyoKun/symfonyMemo/commit/d1563026d229ccf6e91b8da7db26145d74997f4c
